/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vue.pack;

import com.vue.view.AutoSuggestor1;
import com.vue.view.*;
import com.classes.pack.Client;
import com.classes.pack.Produit;
import com.vue.pack.*;
import com.classes.pack.SingletonConnecction;
import com.implementation.pack.Role;
import com.modele_table.pack.BeauteTableau.BeauteQteProduit;
import com.modele_table.pack.BeauteTableau.TableHeader;
import com.modele_table.pack.ModelTable;
import com.modele_table.pack.ModelTable_client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tchatseu
 */
public class vue_produit extends javax.swing.JPanel {

    /**
     * Creates new form vue_produit
     */
    Role r=new Role();
	JOptionPane jop=new JOptionPane();
	List<Produit> lp=new ArrayList<Produit>();
	ModelTable model=new ModelTable();
	JPanel processus =new JPanel();
        AutoSuggestor autoSuggestor;
        
    public vue_produit(JFrame frame)  {
        initComponents();
        processus=this;
       // chargement de tous les produits issus de la base de donnnee
        actualise_table();
        
       
        table_produit.addMouseListener(new remplissage());
        selection_recher.setEditable(true);
        selection_recher.setAutoscrolls(true);
        //chargement des categories et rayon issus de la base de donnée
        String[] lc=r.list_categorie_rayon("categorie");
        String[] lr=r.list_categorie_rayon("rayon");
        setlist_categorie(lc);
        setlist_rayon(lr);
        table_produit.getTableHeader().setDefaultRenderer(new TableHeader());
        table_produit.getColumnModel().getColumn(5).setCellRenderer(new BeauteQteProduit());
        // init_categorie();
        
         autoSuggestor = new AutoSuggestor(valeur_recher, frame, null, Color.gray, Color.white, Color.red, 0.75f) {
            @Override
            boolean wordTyped(String typedWord) {
            	Role r=new Role();
                //create list for dictionary this in your case might be done via calling a method which queries db and returns results as arraylist
                ArrayList<String> words = new ArrayList<>();
               SingletonConnecction sg=new SingletonConnecction();
               Connection co;
               words=Produit.recherche();
                
                setDictionary(words);
                //addToDictionary("bye");//adds a single word

                return super.wordTyped(typedWord);//now call super to check for any matches against newest dictionary
            }
        };
       
      
        frame.pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceuil = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        imprimer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rechercher = new javax.swing.JButton();
        valeur_recher = new javax.swing.JTextField();
        selection_recher = new javax.swing.JComboBox<>();
        l_recherpar = new javax.swing.JLabel();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_produit = new javax.swing.JTable();
        label2 = new java.awt.Label();
        barre_outil = new javax.swing.JToolBar();
        tool_produit = new javax.swing.JButton();
        tool_client = new javax.swing.JButton();
        tool_four = new javax.swing.JButton();
        tool_vente = new javax.swing.JButton();
        tool_entree = new javax.swing.JButton();
        tool_etat_vente = new javax.swing.JButton();
        tool_etat_stock = new javax.swing.JButton();
        tool_depense = new javax.swing.JButton();
        tool_user = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nom_produit = new javax.swing.JTextField();
        l_nompro = new javax.swing.JLabel();
        l_idcathe = new javax.swing.JLabel();
        l_idrayon = new javax.swing.JLabel();
        l_pu = new javax.swing.JLabel();
        actualiser = new javax.swing.JButton();
        prix_uni = new javax.swing.JFormattedTextField();
        ajouter = new javax.swing.JButton();
        categorie = new javax.swing.JComboBox<>();
        rayon = new javax.swing.JComboBox<>();
        l_alert = new javax.swing.JLabel();
        stock_alert = new javax.swing.JFormattedTextField();
        modifier = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        acceuil.setBackground(new java.awt.Color(245, 240, 253));
        acceuil.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        acceuil.setForeground(new java.awt.Color(229, 9, 29));
        acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/home.png"))); // NOI18N
        acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceuilActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(97, 117, 158));
        label1.setText("GESTION DES PRODUITS");

        imprimer.setBackground(new java.awt.Color(245, 240, 253));
        imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/modifier2.png"))); // NOI18N
        imprimer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(245, 240, 253));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/nettoyer.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rechercher.setBackground(new java.awt.Color(245, 240, 253));
        rechercher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 0, 0));
        rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/search.png"))); // NOI18N
        rechercher.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        valeur_recher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        selection_recher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        selection_recher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom produit", "categorie", "rayon", "code produit" }));
        selection_recher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selection_recherActionPerformed(evt);
            }
        });

        l_recherpar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_recherpar.setForeground(java.awt.Color.red);
        l_recherpar.setText("RECHERCHER PAR");

        supprimer.setBackground(new java.awt.Color(245, 240, 253));
        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 0, 0));
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/sup.png"))); // NOI18N
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(l_recherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selection_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valeur_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valeur_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selection_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_recherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(191, 194, 204));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table_produit.setAutoCreateRowSorter(true);
        table_produit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_produit.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        table_produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODE PRODUIT", "NOM PRODUIT", "N° CATEGORIE", "N° RAYON", "PRIX UNITAIRE", "QUANTITE", "STOCK ALERT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_produit.setAutoscrolls(true);
        table_produit.setPreferredSize(new java.awt.Dimension(2000,2000));
        jScrollPane1.setViewportView(table_produit);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(97, 117, 158));
        label2.setText("Formulaire Ajout ");

        barre_outil.setBorder(null);
        barre_outil.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                barre_outilCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        tool_produit.setForeground(new java.awt.Color(97, 117, 158));
        tool_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool.png"))); // NOI18N
        tool_produit.setToolTipText("produit");
        tool_produit.setFocusable(false);
        tool_produit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_produit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_produitActionPerformed(evt);
            }
        });
        barre_outil.add(tool_produit);

        tool_client.setForeground(new java.awt.Color(97, 117, 158));
        tool_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_cli.png"))); // NOI18N
        tool_client.setToolTipText("client");
        tool_client.setFocusable(false);
        tool_client.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_client.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_clientActionPerformed(evt);
            }
        });
        barre_outil.add(tool_client);

        tool_four.setForeground(new java.awt.Color(97, 117, 158));
        tool_four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_four.png"))); // NOI18N
        tool_four.setToolTipText("fournisseur");
        tool_four.setFocusable(false);
        tool_four.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_four.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_fourActionPerformed(evt);
            }
        });
        barre_outil.add(tool_four);

        tool_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_vente.png"))); // NOI18N
        tool_vente.setToolTipText("vente");
        tool_vente.setFocusable(false);
        tool_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_venteActionPerformed(evt);
            }
        });
        barre_outil.add(tool_vente);

        tool_entree.setForeground(new java.awt.Color(97, 117, 158));
        tool_entree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_entre.png"))); // NOI18N
        tool_entree.setToolTipText("client");
        tool_entree.setFocusable(false);
        tool_entree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_entree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_entreeActionPerformed(evt);
            }
        });
        barre_outil.add(tool_entree);

        tool_etat_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_etat_vente.png"))); // NOI18N
        tool_etat_vente.setToolTipText("etat des ventes");
        tool_etat_vente.setFocusable(false);
        tool_etat_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_venteActionPerformed(evt);
            }
        });
        barre_outil.add(tool_etat_vente);

        tool_etat_stock.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_etat_stock.png"))); // NOI18N
        tool_etat_stock.setToolTipText("etat des stocks");
        tool_etat_stock.setFocusable(false);
        tool_etat_stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_stockActionPerformed(evt);
            }
        });
        barre_outil.add(tool_etat_stock);

        tool_depense.setForeground(new java.awt.Color(97, 117, 158));
        tool_depense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_dep.png"))); // NOI18N
        tool_depense.setToolTipText("depense");
        tool_depense.setFocusable(false);
        tool_depense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_depense.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_depense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_depenseActionPerformed(evt);
            }
        });
        barre_outil.add(tool_depense);

        tool_user.setForeground(new java.awt.Color(97, 117, 158));
        tool_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_cli.png"))); // NOI18N
        tool_user.setToolTipText("utilisateurs");
        tool_user.setFocusable(false);
        tool_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_user.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_userActionPerformed(evt);
            }
        });
        barre_outil.add(tool_user);

        nom_produit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_nompro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_nompro.setText("Nom Produit");

        l_idcathe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_idcathe.setText("Cathegorie");

        l_idrayon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_idrayon.setText("Rayon");

        l_pu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_pu.setText("Prix unitaire");

        actualiser.setBackground(new java.awt.Color(245, 240, 253));
        actualiser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        actualiser.setForeground(new java.awt.Color(255, 0, 0));
        actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/refresh5.png"))); // NOI18N
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        prix_uni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        prix_uni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prix_uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_uniActionPerformed(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(245, 240, 253));
        ajouter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 0, 0));
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/add.png"))); // NOI18N
        ajouter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        categorie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieActionPerformed(evt);
            }
        });

        rayon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rayon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rayon1", "rayon2" }));

        l_alert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_alert.setText("Stock Alert");

        stock_alert.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        stock_alert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        modifier.setBackground(new java.awt.Color(245, 240, 253));
        modifier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifier.setForeground(new java.awt.Color(255, 0, 0));
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/modifier.png"))); // NOI18N
        modifier.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_idcathe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_idrayon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_pu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rayon, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prix_uni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categorie, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stock_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(modifier))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l_nompro)
                                .addGap(184, 184, 184)))))
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nompro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categorie, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(l_idcathe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_idrayon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rayon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_pu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(actualiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(283, 283, 283))
        );

        jButton1.setBackground(new java.awt.Color(133, 168, 168));
        jButton1.setText("EXPORTER VIA EXCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barre_outil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barre_outil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceuilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceuilActionPerformed

    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tool_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_fourActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "fournisseur");
    }//GEN-LAST:event_tool_fourActionPerformed

    private void tool_etat_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "journal_vente");
    }//GEN-LAST:event_tool_etat_venteActionPerformed

    private void tool_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_clientActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "client");
    }//GEN-LAST:event_tool_clientActionPerformed

    private void tool_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_client");
    }//GEN-LAST:event_tool_venteActionPerformed

    private void tool_etat_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_stockActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "etat de stock");
    }//GEN-LAST:event_tool_etat_stockActionPerformed

    private void tool_depenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_depenseActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3,"depense");
    }//GEN-LAST:event_tool_depenseActionPerformed

    private void tool_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_userActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "user");
    }//GEN-LAST:event_tool_userActionPerformed

    private void tool_entreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_entreeActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_fournisseur");
    }//GEN-LAST:event_tool_entreeActionPerformed

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:

        actualise_table();
        actualise_panel();
    }//GEN-LAST:event_actualiserActionPerformed

    private void prix_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_uniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prix_uniActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        Produit p=new Produit();
        try{

            //recuperation des valeures dans les champs de saisie
            
            p.setId_categorie((String)categorie.getSelectedItem());
            p.setNum_rayon((String)rayon.getSelectedItem());
            p.setNom_produit(nom_produit.getText());
            p.setPrix_unitaire(Integer.parseInt(prix_uni.getText()));
            p.setAlert(Integer.parseInt(stock_alert.getText()));
            //p.setQuantite(Integer.parseInt(prix_uni.getText()));
            //on recupere la quantite du produit
            String qte= jop.showInputDialog(null,"entrer la quantite initiale en stock","quantite initiale",JOptionPane.INFORMATION_MESSAGE);
            int qte_stock=Integer.parseInt(qte);
            p.setQuantite(qte_stock);

            //operation ajout dans la bd et dans les tables
            if(!r.produit_existe(p.getNom_produit())){
                if(r.ajouter_produit(p)){
                    lp.add(p);
                    model.l_e=lp;
                    table_produit.setModel(model);
                    jop.showMessageDialog(null, "ajout reussi","good",JOptionPane.INFORMATION_MESSAGE);
                    actualise_panel();
                }

                else{
                    jop.showMessageDialog(null, "code produit deja existant","erreur d'ajout",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                jop.showMessageDialog(null, "ce produit existe deja ! verifier son nom","erreur d'ajout",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException n){
            jop.showMessageDialog(null, "veuillez remplir tout vos champs","warming",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_ajouterActionPerformed

    private void categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        //la recherche peut renvoyer un RuntimeException ie pas de produit trouver
        try{
            //on recupere la valeur issue de la categorie � recherchernom=
            String valeur=valeur_recher.getText();

            //on recherche en fonction de sa categorie selectionn�e dans la liste
            if(selection_recher.getSelectedItem()=="nom produit"){
                model.l_e=r.rechercher_Produit("nom_produit",valeur);
            }
            else if(selection_recher.getSelectedItem()=="rayon"){
                model.l_e=r.rechercher_Produit("rayon", valeur);
            }
            else if(selection_recher.getSelectedItem()=="categorie"){

                model.l_e=r.rechercher_Produit("categorie", valeur);
            }
            else{
                int code=Integer.parseInt(valeur_recher.getText());
                model.l_e.clear();
                model.l_e.add(r.rechercher_Produit_code(code));
            }
            table_produit.setModel(model);
            actualise_panel();
        }
        catch(RuntimeException r){
            jop.showMessageDialog(null,"pas de produit correspondant � cette recherche","pas de produit trouver",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rechercherActionPerformed

    private void selection_recherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_recherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_recherActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        Produit p=new Produit();

        try{
            int selection=table_produit.getSelectedRow();
            p=model.l_e.get(selection);

            //p.setQuantite(Integer.parseInt(prix_uni.getText()));
            //operation ajout dans la bd et dans les tables
            int confirmation=jop.showConfirmDialog(null, "voulez vous vraiment modifier le produit de code: " +p.getId_produit(),"confirmation de modification",JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmation==0)
            
                if((r.produit_existe(nom_produit.getText())&&(p.getNom_produit().equals(nom_produit.getText())))||!r.produit_existe(nom_produit.getText())){

                    //recuperation des valeures dans les champs de saisie
                    
                    p.setId_categorie((String)categorie.getSelectedItem());
                    p.setNum_rayon((String)rayon.getSelectedItem());
                    p.setNom_produit(nom_produit.getText());
                    p.setPrix_unitaire(Integer.parseInt(prix_uni.getText()));
                    p.setAlert(Integer.parseInt(stock_alert.getText()));
                    if(r.modifier_produit(p)){
                        actualise_table();
                        jop.showMessageDialog(null, "modification reussie","good",JOptionPane.INFORMATION_MESSAGE);
                        actualise_panel();
                    }

                }
                else{
                    jop.showMessageDialog(null, "ce nouveau produit existe deja!:","erreur de modification",JOptionPane.ERROR_MESSAGE);
                }
           
        }
        catch(NumberFormatException n){
            jop.showMessageDialog(null, "veuillez remplir tout vos chamos","warming",JOptionPane.WARNING_MESSAGE);
        }
        catch(IndexOutOfBoundsException i){
            jop.showMessageDialog(null, "aucune selection de produit","selection requise",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        //int selection=table.getSelectedRow();
        try {

            int selection=table_produit.getSelectedRow();
            Produit p = model.l_e.get(selection);
            int confirmation = jop.showConfirmDialog(null, "voulez vous vraiment supprimer le produit: " + p.getNom_produit(), "confirmation de suppression", JOptionPane.YES_NO_CANCEL_OPTION);
            if (confirmation == 0) {
                if (r.supprimer_produi(p)) {

                    model.l_e.remove(p);
                    jop.showMessageDialog(null, "suppression reussie", "suppression", JOptionPane.INFORMATION_MESSAGE);
                    actualise_panel();
                } else {
                    jop.showMessageDialog(null, "erreur de suppression", "error", JOptionPane.ERROR_MESSAGE);
                }
            }

            //dans le cas ou il choisit plusieurs produit à supprimer
            /*else{
                int confirmation = jop.showConfirmDialog(null, "voulez vous vraiment supprimer tous ses produits ?", "confirmation de suppression", JOptionPane.YES_NO_CANCEL_OPTION);
                if (confirmation==0) {
                    for (int i=0;i<selection.length; i++) {
                        Produit p=new Produit();
                        p = model.l_e.get(selection[i]);
                        if(r.supprimer_produi(p)){
                            model.l_e.remove(p);
                        }
                    }
                    actualise_panel();
                    jop.showMessageDialog(null, "suppression reussie", "suppression", JOptionPane.INFORMATION_MESSAGE);
                }

            }*/
        }
        catch(IndexOutOfBoundsException i){
            jop.showMessageDialog(null, "aucune selection de produit","selection requise",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void barre_outilCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_barre_outilCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_barre_outilCaretPositionChanged

    private void tool_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_produitActionPerformed
        // TODO add your handling code here:
         page_acceuil1.cl.show(page_acceuil1.jPanel3, "produit");
    }//GEN-LAST:event_tool_produitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //creation d'un instance pour recuperer le fichier
        JFileChooser choix = new JFileChooser();

        int retour = choix.showOpenDialog(null);
        if (retour == JFileChooser.APPROVE_OPTION) {
            // un fichier a été choisi (sortie par OK)
            // nom du fichier  choisi 
            choix.getSelectedFile().getName();
            // chemin absolu du fichier choisi
            choix.getSelectedFile().
                    getAbsolutePath();
            int conf=JOptionPane.showConfirmDialog(null, "voulez vraiment effectuer exportation?","demande de confirmation",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
            Produit.export_excel(choix.getSelectedFile());
            actualise_table();
            actualise_panel();
        }
        } else {
            JOptionPane.showMessageDialog(null, "aucune selection de fichier excel au format xls");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 //la classe interne remplissage
    public class remplissage implements MouseListener{

		@Override
		public void mouseClicked(MouseEvent arg0) {
			// TODO Auto-generated method stub
			int selection=table_produit.getSelectedRow();
			Produit p=model.l_e.get(selection);
			
			nom_produit.setText(p.getNom_produit());
			categorie.setSelectedItem(p.getId_categorie());
                        rayon.setSelectedItem(p.getNum_rayon().trim());
			prix_uni.setValue(p.getPrix_unitaire());
                        stock_alert.setValue(p.getAlert());
			
		}

		@Override
		public void mouseEntered(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseExited(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mousePressed(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseReleased(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceuil;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajouter;
    private javax.swing.JToolBar barre_outil;
    private javax.swing.JComboBox<String> categorie;
    private javax.swing.JButton imprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_alert;
    private javax.swing.JLabel l_idcathe;
    private javax.swing.JLabel l_idrayon;
    private javax.swing.JLabel l_nompro;
    private javax.swing.JLabel l_pu;
    private javax.swing.JLabel l_recherpar;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField nom_produit;
    private javax.swing.JFormattedTextField prix_uni;
    private javax.swing.JComboBox<String> rayon;
    private javax.swing.JButton rechercher;
    private javax.swing.JComboBox<String> selection_recher;
    private javax.swing.JFormattedTextField stock_alert;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table_produit;
    private javax.swing.JButton tool_client;
    private javax.swing.JButton tool_depense;
    private javax.swing.JButton tool_entree;
    private javax.swing.JButton tool_etat_stock;
    private javax.swing.JButton tool_etat_vente;
    private javax.swing.JButton tool_four;
    private javax.swing.JButton tool_produit;
    private javax.swing.JButton tool_user;
    private javax.swing.JButton tool_vente;
    private javax.swing.JTextField valeur_recher;
    // End of variables declaration//GEN-END:variables

        public JButton getacceuil(){
    return this.acceuil;
    }
    //methode pour actualiser le panel
    public void actualise_panel(){
         //ici on met tous les formulaire � vide
        
        nom_produit.setText("");
        stock_alert.setText("");
        prix_uni.setText("");
        valeur_recher.setText("");
        
    	processus.repaint();
	processus.validate();
    }
    //on actualise le tableau en affichant tous les produits
    public void actualise_table(){
    	model.l_e=r.affiche_stock("tous");
		table_produit.setModel(model);
                 table_produit.setSelectionMode(0);
                
    }
    //methode pour remplir le combobox
    public void setlist_categorie(String[] lc){
            ComboBoxModel<String> mc=new DefaultComboBoxModel<>(lc);
            this.categorie.setModel(mc);
    }
    public void setlist_rayon(String[] lc){
            
             ComboBoxModel<String> mc=new DefaultComboBoxModel<>(lc);
            this.rayon.setModel(mc);
    }
    
    
}
