/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vue.view;

import com.vue.pack.page_acceuil1;

/**
 *
 * @author DELL
 */
public class barre_outil extends javax.swing.JPanel {

    /**
     * Creates new form barre_outil
     */
    public barre_outil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tool_produit = new javax.swing.JButton();
        tool_client = new javax.swing.JButton();
        tool_four = new javax.swing.JButton();
        tool_vente = new javax.swing.JButton();
        tool_entree = new javax.swing.JButton();
        tool_etat_vente = new javax.swing.JButton();
        tool_etat_stock = new javax.swing.JButton();
        tool_depense = new javax.swing.JButton();
        tool_user = new javax.swing.JButton();
        acceuil = new javax.swing.JButton();

        tool_produit.setBackground(new java.awt.Color(245, 240, 253));
        tool_produit.setForeground(new java.awt.Color(97, 117, 158));
        tool_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/ACC_pro.png"))); // NOI18N
        tool_produit.setToolTipText("produit");
        tool_produit.setFocusable(false);
        tool_produit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_produit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_produitActionPerformed(evt);
            }
        });

        tool_client.setBackground(new java.awt.Color(245, 240, 253));
        tool_client.setForeground(new java.awt.Color(97, 117, 158));
        tool_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/CLI.png"))); // NOI18N
        tool_client.setToolTipText("client");
        tool_client.setFocusable(false);
        tool_client.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_client.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_clientActionPerformed(evt);
            }
        });

        tool_four.setBackground(new java.awt.Color(245, 240, 253));
        tool_four.setForeground(new java.awt.Color(97, 117, 158));
        tool_four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/FOURN.png"))); // NOI18N
        tool_four.setToolTipText("fournisseur");
        tool_four.setFocusable(false);
        tool_four.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_four.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_fourActionPerformed(evt);
            }
        });

        tool_vente.setBackground(new java.awt.Color(245, 240, 253));
        tool_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/vente.png"))); // NOI18N
        tool_vente.setToolTipText("vente");
        tool_vente.setFocusable(false);
        tool_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_venteActionPerformed(evt);
            }
        });

        tool_entree.setBackground(new java.awt.Color(245, 240, 253));
        tool_entree.setForeground(new java.awt.Color(97, 117, 158));
        tool_entree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/email_send.png"))); // NOI18N
        tool_entree.setToolTipText("client");
        tool_entree.setFocusable(false);
        tool_entree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_entree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_entreeActionPerformed(evt);
            }
        });

        tool_etat_vente.setBackground(new java.awt.Color(245, 240, 253));
        tool_etat_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/DEPENSE.png"))); // NOI18N
        tool_etat_vente.setToolTipText("etat des ventes");
        tool_etat_vente.setFocusable(false);
        tool_etat_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_venteActionPerformed(evt);
            }
        });

        tool_etat_stock.setBackground(new java.awt.Color(245, 240, 253));
        tool_etat_stock.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/ET3.png"))); // NOI18N
        tool_etat_stock.setToolTipText("etat des stocks");
        tool_etat_stock.setFocusable(false);
        tool_etat_stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_stockActionPerformed(evt);
            }
        });

        tool_depense.setBackground(new java.awt.Color(245, 240, 253));
        tool_depense.setForeground(new java.awt.Color(97, 117, 158));
        tool_depense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/DEPEN.png"))); // NOI18N
        tool_depense.setToolTipText("depense");
        tool_depense.setFocusable(false);
        tool_depense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_depense.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_depense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_depenseActionPerformed(evt);
            }
        });

        tool_user.setBackground(new java.awt.Color(245, 240, 253));
        tool_user.setForeground(new java.awt.Color(97, 117, 158));
        tool_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/CLI.png"))); // NOI18N
        tool_user.setToolTipText("utilisateurs");
        tool_user.setFocusable(false);
        tool_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_user.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_userActionPerformed(evt);
            }
        });

        acceuil.setBackground(new java.awt.Color(245, 240, 253));
        acceuil.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        acceuil.setForeground(new java.awt.Color(229, 9, 29));
        acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/acc.png"))); // NOI18N
        acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceuilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(tool_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_client, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_four, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_entree, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_etat_vente)
                .addGap(5, 5, 5)
                .addComponent(tool_etat_stock)
                .addGap(5, 5, 5)
                .addComponent(tool_depense, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tool_user, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tool_etat_vente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_etat_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_depense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acceuil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_vente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_produit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tool_entree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tool_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_produitActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "produit");
    }//GEN-LAST:event_tool_produitActionPerformed

    private void tool_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_clientActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "client");
    }//GEN-LAST:event_tool_clientActionPerformed

    private void tool_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_fourActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "fournisseur");
    }//GEN-LAST:event_tool_fourActionPerformed

    private void tool_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_client");
    }//GEN-LAST:event_tool_venteActionPerformed

    private void tool_entreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_entreeActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_fournisseur");
    }//GEN-LAST:event_tool_entreeActionPerformed

    private void tool_etat_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "journal_vente");
    }//GEN-LAST:event_tool_etat_venteActionPerformed

    private void tool_etat_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_stockActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "etat de stock");
    }//GEN-LAST:event_tool_etat_stockActionPerformed

    private void tool_depenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_depenseActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3,"depense");
    }//GEN-LAST:event_tool_depenseActionPerformed

    private void tool_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_userActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "user");
    }//GEN-LAST:event_tool_userActionPerformed

    private void acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceuilActionPerformed
        // TODO add your handling code here:
        page_acceuil1.container.setContentPane(page_acceuil1.getjPanel1());
        page_acceuil1.container.repaint();
        page_acceuil1.container.revalidate();
    }//GEN-LAST:event_acceuilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton acceuil;
    public static javax.swing.JButton tool_client;
    public static javax.swing.JButton tool_depense;
    public static javax.swing.JButton tool_entree;
    public static javax.swing.JButton tool_etat_stock;
    public static javax.swing.JButton tool_etat_vente;
    public static javax.swing.JButton tool_four;
    public static javax.swing.JButton tool_produit;
    public static javax.swing.JButton tool_user;
    public static javax.swing.JButton tool_vente;
    // End of variables declaration//GEN-END:variables
}
