/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vue.view;

import com.classes.pack.Journal_vente;
import com.vue.pack.*;
import com.classes.pack.Produit;
import com.classes.pack.SingletonConnecction;
import com.implementation.pack.Role;
import com.modele_table.pack.BeauteTableau.BeauteQteProduit;
import com.modele_table.pack.BeauteTableau.TableHeader;
import com.modele_table.pack.ModelTable;
import com.modele_table.pack.model_journal_vente;
import com.modele_table.pack.model_stat_hist;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author tchatseu
 */
public class journal_vente_stat1 extends javax.swing.JPanel {

    /**
     * Creates new form vue_produit
     */
 //ma liste de commande
	List<Journal_vente> lc=new ArrayList<Journal_vente>();
        Journal_vente jv=new Journal_vente();
	//mes variables
	JOptionPane jop=new JOptionPane();
         DateFormat dateFormat;
	//panel courant
	private JPanel processus=new JPanel();
        model_journal_vente mj=new model_journal_vente();
        //il faut mettre nos bouttons radio dzans un groupe
        ButtonGroup bg;
        Role r=new Role();
        //objet pour histo
        model_stat_hist model=new model_stat_hist();
    public journal_vente_stat1() throws SQLException, ParseException {
        
        initComponents();
        
        bg=new ButtonGroup();
        //ajout des buttons radia dans le groupe
        bg.add(jour);
        bg.add(mois);
        bg.add(semaine);
        bg.add(tous);
        //traitement des dates
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        date1.setDate(new Date());
        date2.setDate(new Date());
        // Journal_vente journal_vente=new Journal_vente("jour");
       
         jv.setPeriode("jour");
         jv.recup_date();
         
            jv.vente_date("tous");
        
        affichage_resultat();
        tous.setSelected(true);
        table_journal.getTableHeader().setDefaultRenderer(new TableHeader());
        processus=this;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imprimer = new javax.swing.JButton();
        vider = new javax.swing.JButton();
        rechercher = new javax.swing.JButton();
        l_recherpar = new javax.swing.JLabel();
        l_recherpar1 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_journal = new javax.swing.JTable();
        l_recherpar2 = new javax.swing.JLabel();
        jour = new javax.swing.JRadioButton();
        semaine = new javax.swing.JRadioButton();
        mois = new javax.swing.JRadioButton();
        tous = new javax.swing.JRadioButton();
        l_total = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        but_histo = new javax.swing.JButton();

        imprimer.setBackground(new java.awt.Color(245, 240, 253));
        imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/modifier2.png"))); // NOI18N
        imprimer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });

        vider.setBackground(new java.awt.Color(245, 240, 253));
        vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/nettoyer.png"))); // NOI18N
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        rechercher.setBackground(new java.awt.Color(245, 240, 253));
        rechercher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 0, 0));
        rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/search.png"))); // NOI18N
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        l_recherpar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_recherpar.setForeground(java.awt.Color.red);
        l_recherpar.setText("AU");

        l_recherpar1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_recherpar1.setForeground(java.awt.Color.red);
        l_recherpar1.setText("Periode Du");

        date1.setDateFormatString("yyy-MM-dd");

        date2.setDateFormatString("yyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(l_recherpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_recherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imprimer)
                .addGap(1, 1, 1)
                .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(imprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_recherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_recherpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rechercher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
        );

        jScrollPane1.setBackground(new java.awt.Color(191, 194, 204));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table_journal.setAutoCreateRowSorter(true);
        table_journal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_journal.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        table_journal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODE PRODUIT", "NOM PRODUIT", "N° CATEGORIE", "N° RAYON", "PRIX UNITAIRE", "QUANTITE", "STOCK ALERT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_journal.setAutoscrolls(true);
        table_journal.setPreferredSize(new java.awt.Dimension(2000,2000));
        jScrollPane1.setViewportView(table_journal);

        l_recherpar2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_recherpar2.setForeground(java.awt.Color.red);
        l_recherpar2.setText("Filtrer par");

        jour.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jour.setForeground(new java.awt.Color(97, 117, 158));
        jour.setText("JOUR");
        jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourActionPerformed(evt);
            }
        });

        semaine.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        semaine.setForeground(new java.awt.Color(97, 117, 158));
        semaine.setText("SEMAINE");
        semaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semaineActionPerformed(evt);
            }
        });

        mois.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        mois.setForeground(new java.awt.Color(97, 117, 158));
        mois.setText("MOIS");
        mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisActionPerformed(evt);
            }
        });

        tous.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tous.setForeground(new java.awt.Color(97, 117, 158));
        tous.setText("TOUS");
        tous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tousActionPerformed(evt);
            }
        });

        l_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_total.setForeground(java.awt.Color.blue);
        l_total.setText("TOTAL");

        total.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        total.setForeground(java.awt.Color.red);
        total.setText("00");
        total.setToolTipText("");
        total.setOpaque(true);

        but_histo.setBackground(new java.awt.Color(67, 104, 104));
        but_histo.setForeground(java.awt.Color.white);
        but_histo.setText("VOIR HISTOGRAMME");
        but_histo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_histoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_recherpar2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jour)
                        .addGap(18, 18, 18)
                        .addComponent(semaine)
                        .addGap(18, 18, 18)
                        .addComponent(mois)
                        .addGap(18, 18, 18)
                        .addComponent(tous)
                        .addGap(94, 94, 94)
                        .addComponent(but_histo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(l_total, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_recherpar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semaine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tous, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(but_histo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimerActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_viderActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        Date date1=this.date1.getDate();
        Date date2=this.date2.getDate();
        try {
            if(verification_dates(date1, date2)){
                //convertion de la date en String
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String d1 = dateFormat.format(date1);
                String d2 = dateFormat.format(date2);
                jv.setPeriode(d1, d2);
                 
                    jv.vente_date("periode");
                 
                
                affichage_resultat();

            }

        } catch (Exception ex) {
            Logger.getLogger(journal_vente_stat1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_rechercherActionPerformed

    private void jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourActionPerformed
        // TODO add your handling code here:
        
            try {
                jv.setPeriode("jour");
                jv.recup_date();
                
                    jv.vente_date("periode");
                
                affichage_resultat();
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "probleme rencontre");
            }
            try {
                //on recupere les deux dates correspondant a la periode0
                date1.setDate(dateFormat.parse(jv.getDate1()));
                 date2.setDate(dateFormat.parse(jv.getDate2()));
            } catch (ParseException ex) {
                Logger.getLogger(journal_vente_stat1.class.getName()).log(Level.SEVERE, null, ex);
            }
             
    }//GEN-LAST:event_jourActionPerformed

    private void semaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semaineActionPerformed
        // TODO add your handling code here:
        try {
                jv.setPeriode("semaine");
                jv.recup_date();
              
                    jv.vente_date("periode");
                
                affichage_resultat();
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "probleme rencontre");
            }
             
            try {
                //on recupere les deux dates correspondant a la periode0
                date1.setDate(dateFormat.parse(jv.getDate1()));
                 date2.setDate(dateFormat.parse(jv.getDate2()));
            } catch (ParseException ex) {
                Logger.getLogger(journal_vente_stat1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_semaineActionPerformed

    private void moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisActionPerformed
        // TODO add your handling code here:
        try {
                jv.setPeriode("mois");
                jv.recup_date();
               
                    jv.vente_date("periode");
               
                affichage_resultat();
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "probleme rencontre");
            }
        try {
                //on recupere les deux dates correspondant a la periode0
                date1.setDate(dateFormat.parse(jv.getDate1()));
                 date2.setDate(dateFormat.parse(jv.getDate2()));
            } catch (ParseException ex) {
                Logger.getLogger(journal_vente_stat1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_moisActionPerformed

    private void tousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tousActionPerformed
        // TODO add your handling code here:
        
        try {
                
                    jv.vente_date("tous");
               
                affichage_resultat();
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "probleme rencontre");
            }
        
    }//GEN-LAST:event_tousActionPerformed

    private void but_histoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_histoActionPerformed
       
       
       model.l_e=r.bilan("mois");
        
       
       ArrayList<String> nom_des_mois=new ArrayList();
       ArrayList<String> a=new ArrayList();
       ArrayList montant= new ArrayList();
       for(int i=0; i<model.l_e.size(); i++){
           a.add(model.l_e.get(i).getDate());
           montant.add(model.l_e.get(i).getMontant());
       }
       for(int i=0; i<a.size();i++){
           switch (a.get(i)){
               case "1":
                   nom_des_mois.add("JANVIER");
                break;
                 case "2":
                   nom_des_mois.add("FEVRIER");
                break;
                 case "3":
                   nom_des_mois.add("MARS");
                break;
                 case "4":
                   nom_des_mois.add("AVRIL");
                break;
                 case "5":
                   nom_des_mois.add("MAI");
                break;
                 case "6":
                   nom_des_mois.add("JUIN");
                break;
                 case "7":
                   nom_des_mois.add("JUILLET");
                break;
                 case "8":
                   nom_des_mois.add("AOUT");
                break;
                 case "9":
                   nom_des_mois.add("SEPTEMBRE");
                break;
                 case "10":
                   nom_des_mois.add("OCTOBRE");
                break;
                 case "11":
                   nom_des_mois.add("NOVEMBRE");
                break;
                 case "12":
                   nom_des_mois.add("DECEMBRE");
                break;
           }
           
       }
       
       
       Dimension dim=new Dimension(700,650);
        
       drawHistogramme(montant, nom_des_mois,"MONTANT", "PERIODE", "STATISTIQUE MENSUELLE", "STATISTIQUE DE VENTE MENSUELLE", dim);
        

    }//GEN-LAST:event_but_histoActionPerformed

    private void drawHistogramme(ArrayList montant, ArrayList mois, String titreVertical, String titreHorizontal, String titrePaneau, String titreHeader, Dimension dimenssion){
        if(montant.size()==mois.size()){
            DefaultCategoryDataset data= new DefaultCategoryDataset();
            for(int i=0; i<montant.size(); i++){
               data.setValue(Double.parseDouble(montant.get(i).toString()), "montant", mois.get(i).toString()); 
            }
            
            JFreeChart chart=ChartFactory.createStackedBarChart(titreHeader,titreHorizontal,titreVertical, data, PlotOrientation.VERTICAL, false, true, false);
            chart.setBackgroundPaint(Color.white); 
            chart.setBorderVisible(false);
            
            CategoryPlot p=chart.getCategoryPlot();
            
            p.setBackgroundPaint(Color.LIGHT_GRAY);
            
            
            ChartFrame frame=new ChartFrame(titrePaneau, chart);
            frame.setResizable(false);
            frame.setVisible(true);
            frame.setSize(dimenssion);
            frame.setLocationRelativeTo(null);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton but_histo;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton imprimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton jour;
    private javax.swing.JLabel l_recherpar;
    private javax.swing.JLabel l_recherpar1;
    private javax.swing.JLabel l_recherpar2;
    private javax.swing.JLabel l_total;
    private javax.swing.JRadioButton mois;
    private javax.swing.JButton rechercher;
    private javax.swing.JRadioButton semaine;
    private javax.swing.JTable table_journal;
    private javax.swing.JLabel total;
    private javax.swing.JRadioButton tous;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables

   
    
    //methode pour actualiser le panel
     public void actualise_panel(){
                processus.repaint();
 		processus.revalidate();
     }
     //tfonction pour czlculer la periode 
     boolean verification_dates(Date d1,Date d2){
         
         Date curDate=new Date();
         //                Date d1= dateFormat.parse(date1);
//                Date d2= dateFormat.parse(date2);
if(d1.after(d2)){
    JOptionPane.showMessageDialog(null, "la premiere date doit etre inferrieur ou égale à la "
            + "deuxième");
    return false;
}
else if(d1.after(curDate) && d2.after(curDate) ){
    JOptionPane.showMessageDialog(null, "les deux dates sont  supperieurs à la date du jour");
    return false;
}
else  if(d1.after(curDate) && !d2.after(curDate) ){
    JOptionPane.showMessageDialog(null, "la date1 supperieur à la date du jour");
    return false;
}
else if(d2.after(curDate) && !d1.after(curDate)){
    JOptionPane.showMessageDialog(null, "la date2 supperieur à la date du jour");
    return false;
}
         return true;
     }
     
     
     public void affichage_resultat() throws SQLException, ParseException{
                        
                        mj.lv=jv.getListe_vente();
         
                         table_journal.setModel(mj);
                        //on calcul le total des ventes
                         jv.total_vente();
                        total.setText(""+jv.getTotal_final()+" FCFA");
                        actualise_panel();
     }
     
     
}
