/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vue.view;

import com.vue.pack.*;
import com.classes.pack.SingletonConnecction;
import com.classes.pack.Utilisateur;
import com.implementation.pack.Acteur;
import com.implementation.pack.Role;
import com.modele_table.pack.BeauteTableau.BeauteQteProduit;
import com.modele_table.pack.BeauteTableau.TableHeader;
import com.modele_table.pack.ModelTable;
import com.modele_table.pack.ModelTable_user;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tchatseu
 */
public class vue_utilisateur1 extends javax.swing.JPanel {

    /**
     * Creates new form vue_produit
     */
     Acteur r=new Acteur();
	JOptionPane jop=new JOptionPane();
	List<Utilisateur> lp=new ArrayList<Utilisateur>();
	ModelTable_user model=new ModelTable_user();
	JPanel processus =new JPanel();
    public vue_utilisateur1() {
        initComponents();
        processus=this;
        actualise_table();
        table_user.addMouseListener(new remplissage());
        
        table_user.getTableHeader().setDefaultRenderer(new TableHeader());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceuil = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        imprimer = new javax.swing.JButton();
        vider = new javax.swing.JButton();
        l_recherpar = new javax.swing.JLabel();
        type_recherche = new javax.swing.JComboBox<>();
        valeur_recher = new javax.swing.JTextField();
        rechercher = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        tool_produit = new javax.swing.JButton();
        tool_client = new javax.swing.JButton();
        tool_four = new javax.swing.JButton();
        tool_vente = new javax.swing.JButton();
        tool_entree = new javax.swing.JButton();
        tool_etat_vente = new javax.swing.JButton();
        tool_etat_stock = new javax.swing.JButton();
        tool_depense = new javax.swing.JButton();
        tool_user = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JTextField();
        l_login = new javax.swing.JLabel();
        actualiser = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        l_password = new javax.swing.JLabel();
        l_type = new javax.swing.JLabel();
        l_nom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        modifier1 = new javax.swing.JButton();

        acceuil.setBackground(new java.awt.Color(245, 240, 253));
        acceuil.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        acceuil.setForeground(new java.awt.Color(229, 9, 29));
        acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/home.png"))); // NOI18N
        acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceuilActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(97, 117, 158));
        label1.setText("GESTIONS DES UTILISATEURS");

        imprimer.setBackground(new java.awt.Color(245, 240, 253));
        imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/modifier2.png"))); // NOI18N
        imprimer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });

        vider.setBackground(new java.awt.Color(245, 240, 253));
        vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/nettoyer.png"))); // NOI18N
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        l_recherpar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_recherpar.setForeground(java.awt.Color.red);
        l_recherpar.setText("RECHERCHER PAR");

        type_recherche.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        type_recherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "login", "type", "nom" }));
        type_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_rechercheActionPerformed(evt);
            }
        });

        valeur_recher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        rechercher.setBackground(new java.awt.Color(245, 240, 253));
        rechercher.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 0, 0));
        rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/search.png"))); // NOI18N
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(245, 240, 253));
        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 0, 0));
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/sup.png"))); // NOI18N
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_recherpar)
                .addGap(4, 4, 4)
                .addComponent(type_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(valeur_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(imprimer)
                .addGap(1, 1, 1)
                .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_recherpar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valeur_recher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(supprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jScrollPane1.setBackground(new java.awt.Color(191, 194, 204));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table_user.setAutoCreateRowSorter(true);
        table_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_user.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODE PRODUIT", "NOM PRODUIT", "N° CATEGORIE", "N° RAYON", "PRIX UNITAIRE", "QUANTITE", "STOCK ALERT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_user.setAutoscrolls(true);
        table_user.setPreferredSize(new java.awt.Dimension(2000,2000));
        jScrollPane1.setViewportView(table_user);

        jToolBar2.setBorder(null);

        tool_produit.setForeground(new java.awt.Color(97, 117, 158));
        tool_produit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool.png"))); // NOI18N
        tool_produit.setToolTipText("produit");
        tool_produit.setFocusable(false);
        tool_produit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_produit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_produitActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_produit);

        tool_client.setForeground(new java.awt.Color(97, 117, 158));
        tool_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_cli.png"))); // NOI18N
        tool_client.setToolTipText("client");
        tool_client.setFocusable(false);
        tool_client.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_client.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_clientActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_client);

        tool_four.setForeground(new java.awt.Color(97, 117, 158));
        tool_four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_four.png"))); // NOI18N
        tool_four.setToolTipText("fournisseur");
        tool_four.setFocusable(false);
        tool_four.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_four.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_fourActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_four);

        tool_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_vente.png"))); // NOI18N
        tool_vente.setToolTipText("vente");
        tool_vente.setFocusable(false);
        tool_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_venteActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_vente);

        tool_entree.setForeground(new java.awt.Color(97, 117, 158));
        tool_entree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_entre.png"))); // NOI18N
        tool_entree.setToolTipText("client");
        tool_entree.setFocusable(false);
        tool_entree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_entree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_entreeActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_entree);

        tool_etat_vente.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_vente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_etat_vente.png"))); // NOI18N
        tool_etat_vente.setToolTipText("etat des ventes");
        tool_etat_vente.setFocusable(false);
        tool_etat_vente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_vente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_venteActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_etat_vente);

        tool_etat_stock.setForeground(new java.awt.Color(97, 117, 158));
        tool_etat_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_etat_stock.png"))); // NOI18N
        tool_etat_stock.setToolTipText("etat des stocks");
        tool_etat_stock.setFocusable(false);
        tool_etat_stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_etat_stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_etat_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_etat_stockActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_etat_stock);

        tool_depense.setForeground(new java.awt.Color(97, 117, 158));
        tool_depense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_dep.png"))); // NOI18N
        tool_depense.setToolTipText("depense");
        tool_depense.setFocusable(false);
        tool_depense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_depense.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_depense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_depenseActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_depense);

        tool_user.setForeground(new java.awt.Color(97, 117, 158));
        tool_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/tool_cli.png"))); // NOI18N
        tool_user.setToolTipText("utilisateurs");
        tool_user.setFocusable(false);
        tool_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tool_user.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tool_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tool_userActionPerformed(evt);
            }
        });
        jToolBar2.add(tool_user);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(97, 117, 158));
        label2.setText("Formulaire Ajout ");

        login.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        l_login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_login.setText("Login");

        actualiser.setBackground(new java.awt.Color(245, 240, 253));
        actualiser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        actualiser.setForeground(new java.awt.Color(255, 0, 0));
        actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/refresh5.png"))); // NOI18N
        actualiser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(245, 240, 253));
        ajouter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 0, 0));
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/add.png"))); // NOI18N
        ajouter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        l_password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_password.setText("Password");

        l_type.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_type.setText("type");

        l_nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_nom.setText("nom");

        nom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gerant", "magasinier", "vendeur", "caissier" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        modifier1.setBackground(new java.awt.Color(245, 240, 253));
        modifier1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifier1.setForeground(new java.awt.Color(255, 0, 0));
        modifier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vue/view/image_app/modifier.png"))); // NOI18N
        modifier1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(password))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(1, 1, 1)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_login, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualiser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifier1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceuil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceuilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceuilActionPerformed

    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimerActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_viderActionPerformed

    private void tool_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_produitActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "produit");
    }//GEN-LAST:event_tool_produitActionPerformed

    private void tool_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_clientActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "client");
    }//GEN-LAST:event_tool_clientActionPerformed

    private void tool_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_fourActionPerformed
        // TODO add your handling code here
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "fournisseur");
    }//GEN-LAST:event_tool_fourActionPerformed

    private void tool_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_client");
    }//GEN-LAST:event_tool_venteActionPerformed

    private void tool_etat_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_venteActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "journal_vente");
    }//GEN-LAST:event_tool_etat_venteActionPerformed

    private void tool_etat_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_etat_stockActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "etat de stock");
    }//GEN-LAST:event_tool_etat_stockActionPerformed

    private void tool_depenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_depenseActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "depense");
    }//GEN-LAST:event_tool_depenseActionPerformed

    private void tool_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_userActionPerformed
        // TODO add your handling code here:
         page_acceuil1.cl.show(page_acceuil1.jPanel3, "user");
    }//GEN-LAST:event_tool_userActionPerformed

    private void tool_entreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tool_entreeActionPerformed
        // TODO add your handling code here:
        page_acceuil1.cl.show(page_acceuil1.jPanel3, "com_fournisseur");
    }//GEN-LAST:event_tool_entreeActionPerformed

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        //ici on met tous les formulaire � vide

        login.setText("");
        password.setText("");

        nom.setText("");
        actualise_table();
        actualise_panel();
    }//GEN-LAST:event_actualiserActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        try{

            //recuperation des valeures dans les champs de saisie
            Utilisateur u=new Utilisateur(login.getText(),password.getText(),(String)type.getSelectedItem(),nom.getText());

            //operation ajout dans la bd et dans les tables
            if(r.ajouter_user(u)){
                lp.add(u);
                model.l_e=lp;
                table_user.setModel(model);
                jop.showMessageDialog(null, "ajout reussi","good",JOptionPane.INFORMATION_MESSAGE);
                actualise_panel();
            }

            else{
                jop.showMessageDialog(null, "login utilisateur deja existant","erreur d'ajout",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException n){
            jop.showMessageDialog(null, "veuillez remplir tout vos champs","warming",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_ajouterActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void type_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_rechercheActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        //la recherche peut renvoyer un RuntimeException ie pas de produit trouver
        try{
            //on recupere la valeur issue de la categorie � rechercher

            String type=valeur_recher.getText();

            //on recherche en fonction de sa categorie selectionn�e dans la liste
            if(type_recherche.getSelectedItem()=="login"){
                model.l_e=r.rechercher(type,"login");
            }
            else if(type_recherche.getSelectedItem()=="type"){
                model.l_e=r.rechercher(type,"type");
            }
            else if(type_recherche.getSelectedItem()=="nom"){
                model.l_e=r.rechercher(type,"nom");
            }

            
            table_user.setModel(model);
            actualise_panel();
        }
        catch(NumberFormatException n){
            jop.showMessageDialog(null, "veillez saisir dans le champ de recherche","erreur de remplissage",JOptionPane.WARNING_MESSAGE);
        }
        catch(RuntimeException r){
            jop.showMessageDialog(null,"pas d'utilisasteur correspondant à cette recherche","pas de fournisseur trouver",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_rechercherActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        //int selection=table.getSelectedRow();
        try{
            // TODO add your handling code here:
            int selection=table_user.getSelectedRow();
            Utilisateur u=model.l_e.get(selection);
            int confirmation=jop.showConfirmDialog(null, "voulez vous vraiment supprimer l'utilisateur de login : " +u.getLogin(),"confirmation de suppression",JOptionPane.YES_NO_CANCEL_OPTION);
            if(confirmation==0){
                if(r.supprimer_user(u)){

                    model.l_e.remove(u);
                    jop.showMessageDialog(null,"suppression reussie","suppression",JOptionPane.INFORMATION_MESSAGE);
                    actualise_panel();
                }
                else{
                    jop.showMessageDialog(null,"erreur de suppression","error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(IndexOutOfBoundsException i){
            jop.showMessageDialog(null, "aucune selection d'utilisateur","selection requise",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifier1ActionPerformed

     //la classe interne remplissage
    public class remplissage implements MouseListener{

		@Override
		public void mouseClicked(MouseEvent arg0) {
			// TODO Auto-generated method stub
			int selection=table_user.getSelectedRow();
			Utilisateur u=model.l_e.get(selection);
			password.setText(u.getPassword());
			login.setText(u.getLogin());
			
			nom.setText(u.getNom());
		}

		@Override
		public void mouseEntered(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseExited(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mousePressed(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseReleased(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceuil;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton imprimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel l_login;
    private javax.swing.JLabel l_nom;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_recherpar;
    private javax.swing.JLabel l_type;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField login;
    private javax.swing.JButton modifier1;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table_user;
    private javax.swing.JButton tool_client;
    private javax.swing.JButton tool_depense;
    private javax.swing.JButton tool_entree;
    private javax.swing.JButton tool_etat_stock;
    private javax.swing.JButton tool_etat_vente;
    private javax.swing.JButton tool_four;
    private javax.swing.JButton tool_produit;
    private javax.swing.JButton tool_user;
    private javax.swing.JButton tool_vente;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> type_recherche;
    private javax.swing.JTextField valeur_recher;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables

   public JButton getacceuil(){
    return this.acceuil;
    }
     //repaindre le panel en cours
     public void actualise_panel(){
                processus.repaint();
 		processus.validate();
     }
   //on actualise le tableau en affichant tous les fournisseurs
     public void actualise_table(){
     	model.l_e=r.rechercher("","tous");
 		table_user.setModel(model);
                table_user.setSelectionMode(0);
     }
    
}
